### ISSUE TITLE
Add support for gzipped versions of ARC and WARC files

### ISSUE THREAD

**Issue by ibnesayeed** [richardlehane/webarchive#1]
As far as I know, WARC files are compressed per record block basis (correct me if I am wrong). Many archives store WARC files in `warc.gz` format and CDX index has index offset within the compressed binary file which should be very easy to read the block and decompress the buffer.

Fantastic work so far, I am really looking forward for this repository. This will form the basis for many tools. As a side note, I would like to suggest that the name is very generic, it can probably be more specific such as archivereader or something along that line.

**Comment by richardlehane** [comment]
thanks Sawood. I'm happy add in gzip support. 

Have you seen [https://github.com/slyrz/warc](https://github.com/slyrz/warc)? It may have what you need already? I've been working on this for use in [https://github.com/richardlehane/siegfried](https://github.com/richardlehane/siegfried) and it has a lot of quirks relating to that specific use case which might not make it a great general purpose WARC/ARC library.

Happy to work on the name too but archivereader seems even more generic (no web!) & I might add in writers too in the future? Have you any other suggestions? :)

cheers
Richard

**Comment by ibnesayeed** [comment]
Thanks for the pointer to the https://github.com/slyrz/warc library, I was not aware of that.

As they say there are two difficult problems in programming, naming and comments.

I think if this library is mainly to supplement siegfried then you should not worry much about adding features beyond the scope. However, warc library by @slyrz does not include arc files (I guess), so your tool can be more useful where people have mixed set of arc and warc files.

**Comment by richardlehane** [comment]
I've added in support for gzipped ARC and WARC files. I'll hold on the rename at this point, but as I said, definitely open to suggestions, and happy for you to open a separate issue on naming!
All the best
Richard
